### ISSUE TITLE
Not working with certain functions

### ISSUE THREAD

**Issue by jurra** [latentflip/loupe#19] opened 2019-04-17 08:13 UTC
Hi @latentflip, I really like the tool and find it really useful, as I am learning js.
I tried this code in chrome and opera:
```
function greaterThan(n) {
  return m => m > n;
}
let greaterThan10 = greaterThan(10);
console.log(greaterThan10);
console.log(greaterThan10(11));
// → true
```

the behavior is weird, I copied the new code and instead of runing the new code, it runs the default (old) code:
![loupe](https://user-images.githubusercontent.com/18581201/56271733-78b8a200-60f9-11e9-8dae-88b73967f27d.gif)

**Comment by connellrobert** [comment] 2019-12-29 17:19
This was answered in issue #11, the app does not appear to support es6. So the arrow function will not work here.

**Comment by latentflip** [comment] 2022-12-02 19:56
Yeah, it's a dupe of https://github.com/latentflip/loupe/issues/11

**Closed as completed by latentflip** 2022-12-02 19:56 UTC

**Comment by PranavKumar9529desai** [comment] 2023-12-14 07:20
> This was answered in issue #11, the app does not appear to support es6. So the arrow function will not work here.

thanks brother , you saved my time :)
